package:
  name: fastfetch
  version: latest

source:
  git_url: https://github.com/LinusDierheimer/fastfetch.git

about:
  home: https://github.com/LinusDierheimer/fastfetch
  license: MIT
  summary: Like neofetch, but much faster because written in C
  description: "Find recipe here: https://github.com/gvlassis/base_recipes/tree/main/fastfetch"