package:
  name: "fastfetch"
  version: "latest"

source:
  git_url: "https://github.com/LinusDierheimer/fastfetch.git"

requirements:
  build:
    - cmake

about:
  home: "https://github.com/LinusDierheimer/fastfetch"
  license: "MIT"
  summary: "Like neofetch, but much faster because written in C (flashfetch is like fastfetch, but configured at compile time to eliminate any possible overhead)"

extra:
  recipe-maintainers:
    - gvlassis