package:
  name: fastfetch
  version: latest

source:
  git_url: https://github.com/LinusDierheimer/fastfetch.git

requirements:
  build:
    - {{compiler('c')}}
    - cmake
    - make

about:
  home: https://github.com/LinusDierheimer/fastfetch
  license: MIT
  summary: Like neofetch, but much faster because written in C

extra:
  recipe-maintainers:
    - gvlassis