package:
  name: catimg
  version: latest

source:
  git_url: https://github.com/posva/catimg.git

about:
  home: https://posva.net/shell/retro/bash/2013/05/27/catimg
  license: MIT
  summary: Insanely fast image printing in your terminal
  description: "Find recipe here: https://github.com/gvlassis/base_recipes/tree/main/catimg"