package:
  name: atuin
  version: latest

source:
  git_url: https://github.com/ellie/atuin.git

about:
  home: https://atuin.sh/
  license: MIT
  summary: Magical shell history
  description: "Find recipe here: https://github.com/gvlassis/base_recipes/tree/main/atuin"