package:
  name: atuin
  version: latest

source:
  git_url: https://github.com/ellie/atuin.git

requirements:
  build:
    - {{ compiler('rust') }}
    - make

about:
  home: https://github.com/ellie/atuin
  license: MIT
  summary: Magical shell history

extra:
  recipe-maintainers:
    - gvlassis