package:
  name: nnn
  version: latest

source:
  git_url: https://github.com/jarun/nnn.git

about:
  home: https://github.com/jarun/nnn
  license: BSD 2-Clause
  summary: The unorthodox terminal file manager (compiled with O_NERD=1, O_NOSSN=1, O_GITSTATUS=1, O_NAMEFIRST=1)

extra:
  recipe-maintainers:
    - gvlassis