package:
  name: nnn
  version: latest

source:
  git_url: https://github.com/jarun/nnn.git

about:
  home: https://github.com/jarun/nnn
  license: BSD 2-Clause
  summary: The unorthodox terminal file manager (compiled with O_NORL=1, O_NOMOUSE=1, O_NOBATCH=1, O_NOFIFO=1, O_NERD=1, O_NOSSN=1, O_NAMEFIRST=1)
  description: "Find recipe here: https://github.com/gvlassis/base_recipes/tree/main/nnn"